### ISSUE TITLE
Fix publish to PyPi GitHub action

### ISSUE THREAD

**Issue by xaviernogueira** [wesselhuising/pandantic#24]
I went to publish my pandas plugin v0.3.1 to Pypi, but the workflow failed due to your credentials not being verified for TestPyPi:

![Screenshot 2024-09-03 at 3 42 08 PM](https://github.com/user-attachments/assets/94194d49-4a45-4881-8023-9c2040c74a24)

@wesselhuising mind fixing this eventually?

**Comment by wesselhuising** [comment]
Damned, will do this as my first thing tomorrow.

**Comment by wesselhuising** [comment]
Fixed, 0.3.1 is available on pypi.
