### ISSUE TITLE
issue installin in python 3.8

### ISSUE THREAD

**Issue by radvilemaur** [wesselhuising/pandantic#9]
I can't seem to be able to install the package using python 3.8, does it have specific versions it works with?

The error I get is :
 pip install pandantic
Collecting pandantic
  ERROR: Could not find a version that satisfies the requirement pandantic (from versions: none)
ERROR: No matching distribution found for pandantic

I can't find the package itself on pip as well - is this not available atm or any more?

**Comment by radvilemaur** [comment]
works with python 3.9 and later as far as I am aware

**Comment by wesselhuising** [comment]
Hi @radvilemaur ,

I set the python constraints to be equal or higher than 3.9. You couid try forking the repo and change it to a lower python version in the `pyproject.toml` and run `poetry install --lock` to see if the main dependancy also agree on using that lower Python version.

If everything works, you could consider create a PR.

Cheers,

Wessel
